### ISSUE TITLE
"<type>APP_IMAGE</type>" Creates path with over 3200 Chars Length and Crashes the Build

### ISSUE THREAD

**Issue by ingomohr** [petr-panteleyev/jpackage-maven-plugin#15]
## Scenario
GIVEN I am on Windows 10 with Java 21 and Wix3 installed
GIVEN I want to use `--type app-image` in the `jpackage` call, so that I don't get an installer but the app folder instead
WHEN I use `<type>APP_IMAGE</type>` in my plugin configuration
WHEN I call `mvn clean package` and then `mvn jpackage:jpackage`
THEN the build (after 1 minute or so) aborts with error message
   * `Exit code: 1 - java.io.IOException: Cannot access file with path exceeding 32000 characters`

AND
   * I now have a folder of `C:\Users\myUserName\git\hello-jpackage\target\jpackage\hello-jpackage\app\jpackage\hello-jpackage\app\jpackage...`
   * Which apparently recursively contains the jpackage folder in its own app folder
   * Which I can only [remove again via something like 7-Zip File-Manager](https://stackoverflow.com/questions/551072/how-to-delete-a-long-path-in-windows)

### My Configuration in pom.xml
```XML
<plugin>
    <groupId>org.panteleyev</groupId>
    <artifactId>jpackage-maven-plugin</artifactId>
    <version>1.6.5</version>
    <executions>
    <execution>
        <goals>
            <goal>jpackage</goal>
        </goals>
    </execution>
    </executions>
    <configuration>
        <input>${project.build.directory}</input>
        <mainJar>${project.build.finalName}.jar</mainJar>
        <type>APP_IMAGE</type>
        <name>hello-jpackage</name>
        <appVersion>1.0</appVersion> <!-- version prop cannot be used because "0-SNAPSHOT" is illegal -->
        <vendor>MyVendor</vendor>
        <destination>${project.build.directory}/jpackage</destination>
        <winConsole>true</winConsole>
        <javaOptions>
            <option>-Dfile.encoding=UTF-8</option>
        </javaOptions>
    </configuration>
</plugin>
```

**Comment by ingomohr** [comment]
I also tried this w/ `<destination>${project.build.directory}/jpackage-build</destination>` (in case folder "jpackage" is some magic folder in the implementation). Same effect.

**Comment by ingomohr** [comment]
## Workaround
It works with `<destination>jpackage-build</destination>` - i.e. apparently as long I don't use something inside the target folder, the build successfully finishes, and I can run that build.

Problem is that `mvn clean` won't delete that destination folder because it's not in `target`.

**Comment by petr-panteleyev** [comment]
Please show the jpackage output where all command line options are listed.

I might miss this issue because I usually use something like <destination>target/dist</destination> and I works just fine everywhere.

**Comment by petr-panteleyev** [comment]
I've reproduced the issue on one of my projects.

I think the root cause is in &lt;input> option pointing to the same location where you build the app image. Apparently jpackage tries to package somehow recursively in this case.

If you can't avoid using &lt;inpud> then I'd suggest to put &lt;destination> somewhere outside target and configure clean: https://maven.apache.org/plugins/maven-clean-plugin/examples/delete_additional_files.html

**Comment by ingomohr** [comment]
Thank you for getting back to me, @petr-panteleyev ! :) - Your workaround (... somewhere outside target and configure clean...) was what I did eventually to get my build going.

So, if I understand you correctly, it's more like a `jpackage` problem than a problem in the Maven plugin?

**Comment by ingomohr** [comment]
### Works as Specified ✅
