### ISSUE TITLE
Add javadoc for options

### ISSUE THREAD

**Issue by vananiev** [petr-panteleyev/jpackage-maven-plugin#5]
It will be cool to add javadoc for options, so ther can be viewed by editor (for ex. Intellij IDEA).
![2020-11-01_17-49-27](https://user-images.githubusercontent.com/11336712/97806014-9a8d6180-1c6a-11eb-9f54-5e5706f99828.png)

**Comment by petr-panteleyev** [comment]
Resolved in 1.2.1

**Comment by vananiev** [comment]
Thanks.
