### ISSUE TITLE
Forking the lifecycle

### ISSUE THREAD

**Issue by danielsz** [petr-panteleyev/jpackage-maven-plugin#6]
Thank you for this project. 

I was curious:  the Execute [annotation](https://github.com/petr-panteleyev/jpackage-maven-plugin/blob/c0d7e8f66051f249bc5bf928a3ddb5cdfb3d8734/src/main/java/org/panteleyev/jpackage/JPackageMojo.java#L38) has the effect of forking the lifecycle, which is interfering with my Maven workflow. Hopefully it's just me, but what is the rationale?

**Comment by petr-panteleyev** [comment]
Fixed in 1.2.2,
