### ISSUE TITLE
How to set InstallPrivileges for wix for Windows Installer

### ISSUE THREAD

**Issue by MarcoTorres-Hexaware** [petr-panteleyev/jpackage-maven-plugin#9]
Hi,

I am using maven jpackage plugin to create an MSI image. Even though I am using winPerUserInstall it still requires admin privileges to install. Tried to find a way to pass "InstallPrivileges" to wix configuration but was unable to find one.
This is the configuration I have:

`<winShortcut>true</winShortcut>`
`<winDirChooser>true</winDirChooser>`
`<type>MSI</type>`
`<winPerUserInstall>true</winPerUserInstall>`

**Comment by petr-panteleyev** [comment]
Hi.

I've tried to replicate the issue with the following configuration on Windows 11 Home:

```
<execution>
    <id>win</id>
    <configuration>
        <type>MSI</type>
        <icon>icons/icons.ico</icon>
        <winMenu>true</winMenu>
        <winDirChooser>true</winDirChooser>
        <winUpgradeUuid>38dac4b6-91d2-4ca8-aacb-2e0cfd54127a</winUpgradeUuid>
        <winMenuGroup>panteleyev.org</winMenuGroup>
        <winPerUserInstall>true</winPerUserInstall>
    </configuration>
</execution>
```

With this config I see unprivileged install into a user directory.

![image](https://user-images.githubusercontent.com/869839/233476799-00df0e25-40d5-4b04-ac6d-b726c6e54d08.png)

![image](https://user-images.githubusercontent.com/869839/233476899-c93b6e9c-b07d-4bf3-903d-d946a5cccf86.png)

Not sure where the difference is, I usually stay with `<winPerUserInstall>false</winPerUserInstall>`  and enter admin password anyway.

**Comment by MarcoTorres-Hexaware** [comment]
Hi @petr-panteleyev ,

Thanks for you prompt response. 
I did some research and it is not an issue as it seems more a limitation of the jpackage tool. Will close it, below is are my research details for future reference.

When using jpackage it works to install on the user folder, however it still triggers windows UAC (at least on my corporate environment)

After some more research it seems to be a limitation of jpackage itself rather than the plugin.

Wix has two parameters which need to be set to create a package installer that does not require admin permissions [refer to this](https://wixtoolset.org/docs/v3/xsd/wix/package/):
**InstallPrivileges** and **InstallScope**, both should be set by jpackage, but it seems the jpackage tool does not provides the ability to provide the **InstallPrivileges** values, just the **InstallScope**.

Here is the list of parameters supported by jpackage for windows, got them from [here](https://docs.oracle.com/en/java/javase/14/docs/specs/man/jpackage.html), there is no parameter listed for InstallPrivileges:

Windows platform options (available only when running on Windows):
--win-dir-chooser
Adds a dialog to enable the user to choose a directory in which the product is installed.

--win-menu
Adds the application to the system menu.

--win-menu-group menu group name
Start Menu group this application is placed in.

--win-per-user-install
Request to perform an install on a per-user basis.

--win-shortcut
Creates a desktop shortcut for the application.

--win-upgrade-uuid id string
UUID associated with upgrades for this package.

**Comment by petr-panteleyev** [comment]
Well, corporate setup is completely different thing. Like the company may prevent any kind of installations even into the user's local directory.
